version: "3.8"
services:
  devops-worker:
    build:
      context: .
      dockerfile: DevOpsDemo.IndexerWorker/Dockerfile
    container_name: devops-worker
    depends_on:
      - mongo
      - elasticsearch
    environment:
      DOTNET_ENVIRONMENT: "Docker"
    restart: unless-stopped